apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc-app-deployment
  labels:
    app: calc-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: calc-app
  template:
    metadata:
      labels:
        app: calc-app
    spec:
      containers:
      - name: calc-app
        image: sriram312vananam/calculator:1.3
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: calc-app-service  
spec:
  selector:
    app: calc-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
