apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc-app-deployment
  labels:
    app: calc-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: calc-app
  template:
    metadata:
      labels:
        app: calc-app
    spec:
      containers:
      - name: calc-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80